<?php

/*
 * This file is part of the Lugha package.
 *
 * (c) Bernard Ngandu <bernard@devscast.tech>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Devscast\Lugha\Model\Completion\Chat;

/**
 * Enum Role
 *
 * This enum defines the different roles that can exist in the context of a conversational model or system.
 * Each role is represented as a string value, and it can be used to categorize messages based on the source
 * or the function they serve in the conversation.
 *
 * The available roles are:
 * - SYSTEM: A system message that typically sets the context or provides instructions.
 * - USER: A message coming from the user, usually asking a question or giving input.
 * - ASSISTANT: A message generated by the assistant or model in response to the user's message.
 * - TOOL: A message or action that comes from a tool or external system used to perform a task.
 *
 * @author bernard-ng <bernard@devscast.tech>
 */
enum Role: string
{
    case SYSTEM = 'system';
    case USER = 'user';
    case ASSISTANT = 'assistant';
    case TOOL = 'tool';
}
